### ISSUE TITLE
More detail in GitHub API request errors

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-license#28]
We had a PR this morning that didn't get any status set (not even pending). I was able to find this in syslog:

```
Mar  6 13:02:10 cla-01 jquery-license[12865]: Error auditing hook { repo: 'globalize',#012  pr: 410,#012  head: 'a24f26639a6e8f1e3b9685c480e7fa16a5692852',#012  error: 'Error: Not Found\n    at IncomingMessage.<anonymous> (/var/www/jquery-license/node_modules/github-request/lib/request.js:74:14)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:943:16\n    at process._tickCallback (node.js:419:13)' }
```

Without long stack traces, that doesn't provide much insight. All we can tell is that some request failed.

**Comment by jzaefferer** [comment]
We haven't had any issues like this in months, as far as I can tell. Seems safe to ignore.
