### ISSUE TITLE
Check not running for 2 hours

### ISSUE THREAD

**Issue by jzaefferer** [jquery/jquery-license#29]
This PR was created two hours ago (at the time of creating this issue), but the CLA check still hasn't run: https://github.com/jquery/jquery-ui/pull/1502

**Comment by scottgonzalez** [comment]
Same as #28.

```
Mar 16 09:13:29 cla-01 jquery-license[4290]: Error auditing hook { repo: 'jquery-ui',
	  pr: 1502,
	  head: '62907dc56f154f1513e956a49432ac806034d309',
	  error: 'Error: Not Found
    at IncomingMessage.<anonymous> (/var/www/jquery-license/node_modules/github-request/lib/request.js:74:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)' }
```
